name: Documentation
on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # You can replace with your preferred documentation tool
          pip install -r requirements.txt     # If you have additional requirements

      - name: Build documentation
        run: mkdocs build

      # Optional: Run documentation tests
      - name: Test documentation
        run: |
          mkdocs build --strict
          
      # Deploy to GitHub Pages
      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only deploy on push to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Default MkDocs build output directory
