# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Year in HTML files
        run: |
          if grep -Rq "2023" ./*.html; then
            echo "Year 2023 found in HTML files."
          else
            echo "Year 2023 not found in HTML files."
            exit 1
          fi
      
      # Step to install Lychee for link checking
      - name: Install Lychee
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/download/v0.12.0/lychee-v0.12.0-x86_64-unknown-linux-musl.tar.gz | tar xzf - -C /usr/local/bin
      
      # Step to run broken link testing
      - name: Run Broken Link Checker
        run: lychee --verbose .
      
      # Install dependencies including htmlhint
      - name: Install dependencies
        run: |
          npm install --save-dev stylelint-config-standard
          npm install -g htmlhint
          npm ci
      
      # Run Stylelint
      - name: Run Stylelint
        run: npx stylelint '**/*.{css,scss,less}'

      # Run HTMLHint
      - name: Run HTMLHint
        run: htmlhint "**/*.html"

      # Security scanning
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      
      - name: Run Trivy
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .