name: GitHub Actions PR Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-css: # Job for CSS linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --save-dev stylelint-config-standard
      - name: Run Stylelint
        run: npx stylelint '**/*.{css,scss,less}'

  lint-html: # Job for HTML linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install -g htmlhint
      - name: Run HTMLHint
        run: htmlhint "**/*.html"

  check-links: # Job for link checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Lychee
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/download/v0.12.0/lychee-v0.12.0-x86_64-unknown-linux-musl.tar.gz | tar xzf - -C /usr/local/bin
      - name: Run Broken Link Checker
        run: lychee --verbose .

  security-scan: # Job for security scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      - name: Run Trivy
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  # Job for spell checking
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install codespell
        run: sudo apt-get install -y codespell
      - name: Run codespell
        run: codespell "**/*.{js,jsx,ts,tsx,md,html,css,scss,less}"