# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Year in HTML files
        run: |
          if grep -Rq "2024" ./*.html; then
            echo "Year 2024 found in HTML files."
          else
            echo "Year 2024 not found in HTML files."
            exit 1
          fi
          if grep -Rq "20 [0-9][0-3]" ./*.html; then
            echo "Old year found in HTML files."
            exit 1
          else
            echo "No old year found in HTML files."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add steps here!!

      # End additional steps!!
